/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package asd_project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;


public class mainPage extends java.awt.Frame {

    /**
     * Creates new form mainPage
     */
    public mainPage() {
        initComponents();
    }
    Connection conn;
    public void connect()
   {
       try
       {
                         Class.forName("oracle.jdbc.driver.OracleDriver");

            conn=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl","system","bestfriend2368");
            if(conn!=null){
    System.out.println("connected to db");

}else{
        System.out.println("error in connection");

}         
            
                
            
           
            
            
            
           }
       catch(Exception e)
       {
          System.out.println(e.getMessage());
       }
      

   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jTextField2.setFont(new java.awt.Font("Calibri Light", 0, 11)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(0, 0, 1));

        jButton1.setFont(new java.awt.Font("Calibri Light", 1, 11)); // NOI18N
        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox2.setMaximumRowCount(2);
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lowest rate first", "Highest rate first" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Calibri Light", 1, 11)); // NOI18N
        jButton2.setText("VIEW ALL CARS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Calibri Light", 3, 13)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setFont(new java.awt.Font("Calibri Light", 1, 11)); // NOI18N
        jLabel1.setText("CAR ID :");

        jButton3.setFont(new java.awt.Font("Calibri Light", 1, 11)); // NOI18N
        jButton3.setText("RENT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Calibri Light", 1, 11)); // NOI18N
        jButton4.setText("RETURN");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton4))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            connect();
            Statement st=conn.createStatement();
            String query1,query2,query3;
            String search=jTextField2.getText().trim();
         query1="select * from cartab where carname like '%"+search+"%' or carcomp like '%"+search+"%' or color like '%"+search+"%' and ownid is null order by rate asc";
         query2="select * from cartab where carname like '%"+search+"%' or carcomp like '%"+search+"%' or color like '%"+search+"%' and ownid is null order by rate desc";
        query3="select * from cartab";
        if(jComboBox2.getSelectedIndex()==0){
                ResultSet rs1=st.executeQuery(query1);
                jTextArea1.setText("");
                while(rs1.next()){
                    String rate=rs1.getString("RATE");
                    String id=rs1.getString("CARID");
                    String carname=rs1.getString("CARNAME");
                    String carcomp=rs1.getString("CARCOMP");
                    String color=rs1.getString("COLOR");
                    jTextArea1.append("\nID :  "+id+"\nCARNAME :  "+carname+"\nCARCOMP :  "+carcomp+"\nCOLOR :  "+color+"\nRATE :  "+rate+"\n===============================================================");
                }
            }
                
            if(jComboBox2.getSelectedIndex()==1){
                jTextArea1.setText("");
                ResultSet rs2=st.executeQuery(query2);
                while(rs2.next()){
                    String rate=rs2.getString("RATE");
                    String id=rs2.getString("CARID");
                    String carname=rs2.getString("CARNAME");
                    String carcomp=rs2.getString("CARCOMP");
                    String color=rs2.getString("COLOR");
                    jTextArea1.append("\nID :  "+id+"\nCARNAME :  "+carname+"\nCARCOMP :  "+carcomp+"\nCOLOR :  "+color+"\nRATE :  "+rate+"\n=============================================================");
                }
            }
        }
        catch(Exception e){
            System.out.println("asd_project.mainPage.jButton1ActionPerformed()");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    try{
        String id=jTextField1.getText();
    String q="update cartab set ownid='1' where carid='"+id+"'";
connect();
Statement st=conn.createStatement();
        ResultSet rs=st.executeQuery(q);
    }
    catch(Exception e){
        System.out.println("asd_project.mainPage.jButton3ActionPerformed()");
    }
        

// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
try{connect();
        String id=jTextField1.getText();
    String q="update cartab set ownid='' where carid='"+id+"'";
Statement st=conn.createStatement();
ResultSet rs=st.executeQuery(q);
    popup po=new popup(jTextField1.getText());
            po.setVisible(true);
            this.setVisible(false);

            
}
    catch(Exception e){
        System.out.println(e);
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
try{
     connect();
String q;
q="select * from cartab where ownid is null";
Statement st=conn.createStatement();
ResultSet rs=st.executeQuery(q);
jTextArea1.setText(" ");
while(rs.next()){
    String rate=rs.getString("RATE");
    String id=rs.getString("CARID");
    String carname=rs.getString("CARNAME");
    String carcomp=rs.getString("CARCOMP");
    String color=rs.getString("COLOR");
    jTextArea1.append("\nID :  "+id+"\nCARNAME :  "+carname+"\nCARCOMP :  "+carcomp+"\nCOLOR :  "+color+"\nRATE :  "+rate+"\n=============================================================");
                
}
}
catch(Exception e){
    System.out.println("asd_project.mainPage.jButton2ActionPerformed()");
}
       // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainPage().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
